/* --------------------------------------------------------
 * This code was generated automatically by MBsysC modules.
 * MBsysC modules are distributed as part of the ROBOTRAN 
 * software. They provides functionalities for dealing with
 * symbolic equations generated by ROBOTRAN. 
 *
 * More info on www.robotran.be 
 *
 * Universite catholique de Louvain, Belgium 
 *
 * Last update : Sun May 31 21:41:08 2020
 * --------------------------------------------------------
 *
 */
#include "mbs_path.h"
#include "user_model.h"
#include "mbs_xml_reader.h"
#include "mbs_load_xml.h"
#include "useful_functions.h"
#include "math.h"

// ============================================================ //


UserModel* mbs_new_user_model() 
{
    UserModel* um;
    um = (UserModel*)malloc(sizeof(UserModel));
    return um;
}

void mbs_delete_user_model(UserModel* um) 
{
    free(um);
}

 void mbs_load_user_model_xml(MDS_gen_strct* gen, UserModel* um) 
{

    int ind_state_value = 1;

}

 void mbs_bind_user_model(MDS_gen_strct* gen, UserModel* um) 
{


}
 void mbs_print_user_model(UserModel* um) 
{

}

// ============================================================ //
 
