/* --------------------------------------------------------
 * This code was generated automatically by MBsysC modules.
 * MBsysC modules are distributed as part of the ROBOTRAN 
 * software. They provides functionalities for dealing with
 * symbolic equations generated by ROBOTRAN. 
 *
 * More info on www.robotran.be 
 *
 * Universite catholique de Louvain, Belgium 
 *
 * Last update : Sun May 31 21:41:08 2020
 * --------------------------------------------------------
 *
 */
#include <stdlib.h>
#include "user_IO.h"

// ============================================================ //


UserIO* mbs_new_user_IO(UserIoInfo* ioInfo) 
{
    UserIO *uio;
    uio = (UserIO*) malloc(sizeof(UserIO));

    return uio;
}



void mbs_delete_user_IO(UserIO *uio)
{

    free(uio);
}

// ============================================================ //
 
