/* --------------------------------------------------------
 * This code was generated automatically by MBsysC modules.
 * MBsysC modules are distributed as part of the ROBOTRAN 
 * software. They provides functionalities for dealing with
 * symbolic equations generated by ROBOTRAN. 
 *
 * More info on www.robotran.be 
 *
 * Universite catholique de Louvain, Belgium 
 *
 * Last update : Sun May 31 21:41:08 2020
 * --------------------------------------------------------
 *
 */
#ifndef USER_ALL_ID_h
#define USER_ALL_ID_h

// ============================================================ //


// joint

#define Joint_0_id 1
#define Joint_1_id 2
#define Joint_2_id 3
#define Joint_3_id 4
#define Joint_4_id 5
#define Joint_5_id 6
#define Joint_6_id 7
#define Joint_7_id 8
#define Joint_8_id 9


// body

#define Body_1_id 1
#define Body_2_id 2
#define Body_3_id 4
#define Body_4_id 5
#define Body_5_id 6
#define Body_6_id 8
#define Body_7_id 9


// point

#define Body_1_Point_0_id 1
#define Body_1_Point_1_id 2
#define Body_2_Point_0_id 3
#define Body_3_Point_0_id 4
#define Body_5_Point_0_id 5
#define Body_6_Point_0_id 6


// sensor



// extforce



// links



// Rods



// ============================================================ //

# endif
