/* --------------------------------------------------------
 * This code was generated automatically by MBsysC modules.
 * MBsysC modules are distributed as part of the ROBOTRAN 
 * software. They provides functionalities for dealing with
 * symbolic equations generated by ROBOTRAN. 
 *
 * More info on www.robotran.be 
 *
 * Universite catholique de Louvain, Belgium 
 *
 * Last update : Sun May 31 21:41:08 2020
 * --------------------------------------------------------
 *
 */
#ifndef USER_HARD_PARAM_h
#define USER_HARD_PARAM_h

// ============================================================ //


// gravity
#define G_3 9.81

// mass
#define M_1 1000
#define M_2 200
#define M_4 5
#define M_5 70
#define M_6 200
#define M_8 5
#define M_9 70

// center of mass
#define L_3_1 -2.5
#define L_1_2 -1.5
#define L_3_4 1.5
#define L_1_6 1.5
#define L_3_8 1.5

// inertia
#define IN_1_1 2145
#define IN_5_1 2145
#define IN_9_1 125
#define IN_1_2 10.875
#define IN_5_2 151
#define IN_9_2 159
#define IN_1_4 3.75
#define IN_5_4 3.75
#define IN_1_5 28
#define IN_5_5 28
#define IN_9_5 28
#define IN_1_6 10.875
#define IN_5_6 151
#define IN_9_6 159
#define IN_1_8 3.75
#define IN_5_8 3.75
#define IN_1_9 28
#define IN_5_9 28
#define IN_9_9 28

// body point
#define DPT_1_1 -0.5
#define DPT_3_1 -5
#define DPT_1_2 0.5
#define DPT_3_2 -5
#define DPT_1_3 -3
#define DPT_3_3 0.15
#define DPT_3_4 3
#define DPT_1_5 3
#define DPT_3_5 0.15
#define DPT_3_6 3

// ============================================================ //

# endif
